"""Appendix A of the technical note: one row per labelled result, generated from release/public/CLAIMS.md.
Run: uv run --project sim python sim/scripts/technote_verification_table.py
Writes notes/technote/verification_table_{en,pt}.tex (longtable rows; the note \\input's them).
"""
from __future__ import annotations

import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
CLAIMS = ROOT / "release" / "public" / "CLAIMS.md"
OUT = ROOT / "notes" / "technote"

KIND = {   # evidence per claim: short label (en, pt); default from the status prefix
    "C-011": ("numeric + hand", "numérico + à mão"),
    "C-016": ("Lean + numeric", "Lean + numérico"),
    "C-015": ("numeric; Lean (density)", "numérico; Lean (densidade)"),
    "C-017": ("Lean + hand", "Lean + à mão"),
    "C-018": ("hand + Lean ($\\mathrm{II}\\ne0$)", "à mão + Lean ($\\mathrm{II}\\ne0$)"),
    "C-029": ("hand + numeric", "à mão + numérico"),
    "C-030": ("numeric (certified)", "numérico (certificado)"),
}
PREFIX = {"proved-lean": ("Lean", "Lean"), "verified-numeric": ("numeric", "numérico"), "argued": ("hand", "à mão")}
HEAD = {
    "en": ("ID", "Result", "Evidence", "Lean theorems", "Scripts and tests"),
    "pt": ("ID", "Resultado", "Evidência", "Teoremas em Lean", "Scripts e testes"),
}


def tex(s: str) -> str:
    s = s.replace("\\", "\\textbackslash{}").replace("_", "\\_\\allowbreak{}").replace("{", "\\{").replace("}", "\\}")
    s = s.replace("\\textbackslash\\{\\}", "\\textbackslash{}").replace("\\_\\allowbreak\\{\\}", "\\_\\allowbreak{}")
    s = s.replace("/", "/\\allowbreak{}").replace(".", ".\\allowbreak{}")
    for u, m in (("θ", "\\ensuremath{\\theta}"), ("Δ", "\\ensuremath{\\Delta}")):
        s = s.replace(u, m)
    return s


def is_code(tok: str) -> bool:
    return tok.startswith(("test_", "sim", "nleaflet.", "deliverable")) or "/" in tok or tok.endswith((".py", ".txt", ".json", ".csv"))


def rows(lang: str):
    out = []
    for line in CLAIMS.read_text(encoding="utf-8").splitlines():
        m = re.match(r"\| (C-\d{3}) \|", line)
        if not m:
            continue
        cid = m.group(1)
        cells = [c.strip() for c in line.strip().strip("|").split(" | ")]
        status, evidence = cells[3], cells[4]
        kind = KIND.get(cid) or next(v for k, v in PREFIX.items() if status.startswith(k))
        toks = re.findall(r"`([^`]+)`", evidence)
        lean = [t for t in toks if not is_code(t)]
        code = [t for t in toks if is_code(t)]
        if not toks:
            code = [evidence]
        k = kind[0] if lang == "en" else kind[1]
        lean_s = ", ".join(f"\\texttt{{{tex(t)}}}" for t in lean) or "--"
        code_s = ", ".join(f"\\texttt{{{tex(t)}}}" if toks else tex(t) for t in code) or "--"
        out.append(f"{cid} & \\cref{{claim:{cid}}} & {k} & {lean_s} & {code_s}\\\\")
    return out


def write(lang: str):
    h = HEAD[lang]
    body = "\n".join(rows(lang))
    doc = (
        "% generated by sim/scripts/technote_verification_table.py from release/public/CLAIMS.md\n"
        "\\setlength{\\LTleft}{0pt}\\setlength{\\LTright}{0pt}\n"
        "\\begin{longtable}{@{}l>{\\raggedright}p{0.15\\textwidth}>{\\raggedright}p{0.12\\textwidth}"
        ">{\\raggedright}p{0.285\\textwidth}>{\\raggedright\\arraybackslash}p{0.25\\textwidth}@{}}\n"
        "\\toprule\n" + " & ".join(f"\\textbf{{{x}}}" for x in h) + "\\\\\\midrule\\endhead\n"
        "\\bottomrule\\endfoot\n" + body + "\n\\end{longtable}\n"
    )
    (OUT / f"verification_table_{lang}.tex").write_text(doc, encoding="utf-8")


if __name__ == "__main__":
    write("en"); write("pt")
    print("rows:", len(rows("en")))
